[package]
name = "my_game"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

bevy = { version = "0.18", default-features = false, features = [
    "default_app",
    "default_platform",
    "debug",
] }

bevy_kira_audio = { version = "0.25" }

bevy_asset_loader = "0.26"
bevy_common_assets = { version = "0.15", features = ["ron"] }

leafwing-input-manager = { version = "0.20" }

avian3d = { version = "0.6" }
