[package]
name = "my_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18", features = ["2d"] }

serde = { version = "1.0", features = ["derive"] }
bevy_asset_loader = "0.26"
bevy_common_assets = { version = "0.15", features = ["ron"] }

leafwing-input-manager = { version = "0.20" }
seldom_state = { version = "0.16", features = ["leafwing_input"] }

avian2d = { version = "0.5" }
bevy_ecs_tiled = { version = "0.11", features = ["avian", "user_properties"] }
